    LIST P=16F877A
    INCLUDE     "P16F877A.INC"
    __CONFIG	_XT_OSC  & _WDT_OFF & _LVP_OFF
    COUNTER EQU 0x20
    RIGHT   EQU 0x21
    LEFT    EQU 0x22
    VAR1    EQU 0x23	
    ORG	    0X00
    GOTO    INIT
    ORG	    0X04
    GOTO    INTERRUPT
INIT
    BSF	    STATUS,5
    CLRF    TRISB
    CLRF    TRISA
    BSF	    PIE1,TMR1IE
    BCF	    STATUS,5
    MOVLW   B'00110001'
    MOVWF   T1CON
    CLRF    PIR1
    MOVLW   B'11000000'
    MOVWF   INTCON  
    MOVLW   0X0B
    MOVWF   TMR1H
    MOVLW   0XDC
    MOVWF   TMR1L
    CLRF    RIGHT
    CLRF    LEFT
    CLRF    COUNTER
MAIN
    BSF	    PORTA,1
    BCF	    PORTA,0
    MOVF    RIGHT, W
    CALL    LOOK_UP
    MOVWF   PORTB
    CALL    DELAY
    BCF	    PORTA,1
    BSF	    PORTA,0
    MOVF    LEFT, W
    CALL    LOOK_UP
    MOVWF   PORTB
    CALL    DELAY
    GOTO    MAIN
   
INTERRUPT
    BCF	    INTCON,GIE
    BCF	    INTCON,PEIE   
    BTFSS   PIR1,TMR1IF
    GOTO    INTERRUPT_END
    BCF	    PIR1,TMR1IF
    MOVLW   0X0B
    MOVWF   TMR1H
    MOVLW   0XDC
    MOVWF   TMR1L
    INCF    COUNTER
    MOVF    COUNTER,W
    SUBLW   D'2'
    BTFSC   STATUS,Z
    GOTO    RIGHT_INCREMENT
    GOTO    INTERRUPT_END
RIGHT_INCREMENT
    CLRF    COUNTER
    INCF    RIGHT
    MOVF    RIGHT,W
    SUBLW   D'10'
    BTFSC   STATUS,Z
    GOTO    LEFT_INCREMENT
    GOTO    INTERRUPT_END
LEFT_INCREMENT
    CLRF    RIGHT
    INCF    LEFT
    MOVF    LEFT, W
    SUBLW   D'6'
    BTFSC   STATUS,Z
    CLRF    LEFT
    GOTO    INTERRUPT_END
INTERRUPT_END 
    BSF	    INTCON,GIE
    BSF	    INTCON,PEIE
    RETFIE
 
DELAY
    CLRF    VAR1
DELAY2
    DECFSZ  VAR1
    GOTO    DELAY2
    RETURN
    
LOOK_UP   
    ADDWF   PCL
    RETLW   B'00111111'    
    RETLW   B'00000110'    
    RETLW   B'01011011'    
    RETLW   B'01001111'    
    RETLW   B'01100110'    
    RETLW   B'01101101'    
    RETLW   B'01111101'    
    RETLW   B'00000111'    
    RETLW   B'01111111'    
    RETLW   B'01101111'        
 
    END